version: '3'

services:
    database:
        image: 'postgres:latest'
        container_name: database
        hostname: database
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_DB=$POSTGRES_DB
    backend:
        environment:
            - COGNITO_REGION=$COGNITO_REGION
            - COGNITO_POOL_ID=$COGNITO_POOL_ID
            - COGNITO_CLIENT_SECRET=$COGNITO_CLIENT_SECRET
            - COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
            args:
                - DATABASE_URL=${DATABASE_URL}
        volumes:
            - ./backend/:/user/app
        container_name: backend-api
        expose:
            - '3001'
            - '5555'
        ports:
            - '3001:3001'
            - '5555:5555'
        command: npm run start
        depends_on:
            - database
