version: '3'

services:
    backend:
        container_name: backend
        hostname: backend
        environment:
            - COGNITO_REGION=$COGNITO_REGION
            - COGNITO_POOL_ID=$COGNITO_POOL_ID
            - COGNITO_CLIENT_SECRET=$COGNITO_CLIENT_SECRET
            - COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
            args:
                - DATABASE_URL=${DATABASE_URL}
        volumes:
            - ./backend/:/user/app
        expose:
            - 3001
            - 5555
        ports:
            - 3001:3001
            - 5555:5555
        depends_on:
            - postgres
        command: >
            bash -c "npx prisma migrate dev
            && npx prisma db seed
            && yarn start"
    postgres:
        image: 'postgres:latest'
        container_name: postgres
        hostname: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_DB=$POSTGRES_DB
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
